### ISSUE TITLE
Tensor product of Noetherian modules is Noetherian

### ISSUE THREAD

**Issue by marmistrz** [jakpal/commalg#1]
This follows from right-exactness: https://math.stackexchange.com/questions/245771/tensor-product-of-noetherian-modules

The algebraic closure of integers tensored with itself is not a counter-example, because \bar{Q} it's not Noetherian itself, because it's not finitely generated; or see this link for an example of an infinite ascending chain of ideals: https://math.stackexchange.com/questions/1820304/what-is-an-easy-example-of-non-noetherian-domain

**Comment by jakpal** [comment]
The point about tensor products is quite valid. Addressed by f6bdcb795456fa3c2ad9a601fe99df970e2a9e05 .

I am confused about \bar{\rational}. It is a field and so has only maximal ideals; it is thus Noetherian as a ring. Rather, we are interested in an infinitely ascending chain of \rational-submodules in order to show that it is not a Noetherian \rational-module.

**Comment by marmistrz** [comment]
\bar{\Q} is definitely a Noetherian \bar{\Q}-module, but not a Noetherian \Q-module. The tensor product was taken over \Q, so here the latter is relevant.

**Comment by jakpal** [comment]
What I am calling into question is whether https://math.stackexchange.com/questions/1820304/what-is-an-easy-example-of-non-noetherian-domain establishes that the closure of Q is not Noetherian over Q.

Edit: I am being pedantic in this, seems one can show the same easily another way.
